#!/usr/bin/env bash

# Get Volume
get_volume() {
	volume=`amixer get Master | tail -n1 | awk -F ' ' '{print $5}' | tr -d '[]'`
	echo "$volume"
}

# Get icons
get_icon() {
	vol="$(get_volume)"
	current="${vol%%%}"
	if [[ "$current" -eq "0" ]]; then
		icon=""
	elif [[ ("$current" -ge "0") && ("$current" -le "30") ]]; then
		icon=""
	elif [[ ("$current" -ge "30") && ("$current" -le "60") ]]; then
		icon=""
	elif [[ ("$current" -ge "60") && ("$current" -le "100") ]]; then
		icon=""
	fi
}

# Notify
notify_user() {
	notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i " " " $icon Volume : $(get_volume)"
}

# Increase Volume
inc_volume() {
	amixer -Mq set Master,0 5%+ unmute && get_icon && notify_user
}

# Decrease Volume
dec_volume() {
	amixer -Mq set Master,0 5%- unmute && get_icon && notify_user
}

# Toggle Mute
toggle_mute() {
	status=`amixer get Master | tail -n1 | grep -wo 'on'`

	if [[ "$status" == "on" ]]; then
		amixer set Master toggle && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i " " "  Mute"
	else
		amixer set Master toggle && get_icon && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i " " " $icon Unmute"
	fi
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
	get_volume
elif [[ "$1" == "--inc" ]]; then
	inc_volume
elif [[ "$1" == "--dec" ]]; then
	dec_volume
elif [[ "$1" == "--toggle" ]]; then
	toggle_mute
else
	get_volume
fi

