code --install-extension GitHub.copilot &&
code --install-extension Prisma.prisma &&
code --install-extension vscodevim.vim &&
code --install-extension esbenp.prettier-vscode &&
code --install-extension WakaTime.vscode-wakatime &&
code --install-extension kamikillerto.vscode-colorize &&
code --install-extension streetsidesoftware.code-spell-checker &&
code --install-extension bradlc.vscode-tailwindcss &&
code --install-extension formulahendry.auto-rename-tag &&
code --install-extension mechatroner.rainbow-csv &&
code --install-extension aaron-bond.better-comments &&
code --install-extension dbaeumer.vscode-eslint &&
code --install-extension stylelint.vscode-stylelint &&
code --install-extension miguelsolorio.symbols &&
code --install-extension usernamehw.errorlens &&
code --install-extension drcika.apc-extension &&
code --install-extension ritwickdey.LiveServer &&
code --install-extension formulahendry.auto-close-tag &&
code --install-extension kaiwood.center-editor-window &&
code --install-extension streetsidesoftware.code-spell-checker-portuguese
